version: '3'

services:
  postgresql:
    image: postgres
    container_name: testnest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testnest
    command: postgres
    restart: always
